name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cPanel Git Deployment
        run: |
          curl -s -X POST \
            "https://165.140.68.97:2083/execute/VersionControlDeployment/create" \
            -k \
            -H "Authorization: cpanel sealifee:${{ secrets.CPANEL_API_TOKEN }}" \
            --data-urlencode "repository_root=/home/sealifee/repositories/sunwave-git"
